/**
 * Segment list -> `<a:txBody>` XML.
 *
 * The guiding rule is *reuse over recreation*: whenever a segment still maps to
 * its original run with unchanged text and no formatting override, the original
 * `<a:r>` node is spliced back in untouched. Only genuinely new or changed text
 * gets a freshly built run, and even then its `<a:rPr>` is cloned from the run
 * it came from. That way an edit to one word in a paragraph leaves every other
 * run — and every property we never parsed — byte-identical.
 */
import {
  child,
  createElement,
  cloneNode,
  localName,
  setAttr,
  type XmlNode,
} from '../../oxml/xml.js';
import type { Paragraph, TextRun } from '../model.js';
import { applyFormat, stripHyperlink } from './format.js';
import { applyParaFormat, ensureParaProps, resolvedOf } from './paraProps.js';
import { isEmptyFormat, type ParaFormat, type RunFormat } from '../../oxml/edit/format.js';

/** One contiguous stretch of text that shares formatting. */
export interface Segment {
  text: string;
  /** The model run this text inherits its `<a:rPr>` from, if any. */
  src?: TextRun;
  /** Toolbar override applied on top of the source run's properties. */
  format?: RunFormat;
  /** A line break (`<a:br>`) rather than literal text. */
  isBreak?: boolean;
}

/** A paragraph after editing: the source it came from, plus its new content. */
export interface ParaEdit {
  /** The model paragraph this maps to; undefined for a newly created one. */
  src?: Paragraph;
  segments: Segment[];
  /**
   * Paragraph-level formatting the toolbar asked for — list, level, alignment,
   * spacing. Applied to this paragraph's own `<a:pPr>`, so the two halves of an
   * Enter-split can be formatted independently even though they share a source.
   */
  format?: ParaFormat;
}

/** Resolves a model object back to the XML node it was parsed from. */
export type SourceLookup = (model: object) => { node: XmlNode } | undefined;

/** Namespace prefix of a qualified name ("a:t" -> "a"), or "" if unprefixed. */
function prefixOf(name: string): string {
  const i = name.indexOf(':');
  return i === -1 ? '' : name.slice(0, i);
}

/**
 * The DrawingML prefix in use in this text body, learned from an existing node
 * rather than assumed — files from other producers may not use "a:".
 */
function drawingPrefix(txBody: XmlNode): string {
  const firstP = txBody.children.find((c) => localName(c.name) === 'p');
  if (firstP) {
    const inner = firstP.children.find((c) => ['r', 'br', 'fld', 'pPr'].includes(localName(c.name)));
    if (inner) return prefixOf(inner.name);
    return prefixOf(firstP.name);
  }
  const bodyPr = txBody.children.find((c) => localName(c.name) === 'bodyPr');
  return bodyPr ? prefixOf(bodyPr.name) : 'a';
}

/**
 * Text needs `xml:space="preserve"` when it has leading or trailing whitespace,
 * otherwise a consumer is free to trim it away.
 */
function makeTextNode(prefix: string, text: string): XmlNode {
  const q = prefix ? `${prefix}:t` : 't';
  const node = createElement(q, {}, [], text);
  if (text !== text.trim()) setAttr(node, 'xml:space', 'preserve');
  return node;
}

/** The `<a:rPr>` of a source run node, cloned so the original is untouched. */
function cloneRPr(srcNode: XmlNode | undefined, prefix: string): XmlNode {
  const existing = srcNode ? child(srcNode, 'rPr') : undefined;
  if (existing) {
    const clone = cloneNode(existing);
    // A cloned rPr keeps its own name, which already carries the right prefix.
    return clone;
  }
  return createElement(prefix ? `${prefix}:rPr` : 'rPr');
}

/** True if the segment can reuse its source node verbatim. */
function canReuse(seg: Segment, srcNode: XmlNode | undefined): boolean {
  if (!srcNode || !isEmptyFormat(seg.format)) return false;
  const tag = localName(srcNode.name);
  if (seg.isBreak) return tag === 'br';
  if (tag === 'br') return false;
  // A field's text is generated by PowerPoint; reuse only while it is unchanged.
  const currentText = child(srcNode, 't')?.text ?? '';
  return currentText === seg.text;
}

function buildRunNode(seg: Segment, lookup: SourceLookup, prefix: string): XmlNode {
  const srcNode = seg.src ? lookup(seg.src)?.node : undefined;

  if (canReuse(seg, srcNode)) return srcNode!;

  const rPr = cloneRPr(srcNode, prefix);
  if (seg.format && !isEmptyFormat(seg.format)) applyFormat(rPr, seg.format, prefix);

  if (seg.isBreak) {
    return createElement(prefix ? `${prefix}:br` : 'br', {}, [rPr]);
  }

  // Re-typed text is no longer the link's label, and a field whose text was
  // edited stops being a field — both become plain runs.
  if (srcNode && ['fld', 'r'].includes(localName(srcNode.name))) stripHyperlink(rPr);

  return createElement(prefix ? `${prefix}:r` : 'r', {}, [rPr, makeTextNode(prefix, seg.text)]);
}

/**
 * Build one `<a:p>`: the source paragraph's `<a:pPr>` and `<a:endParaRPr>` are
 * carried over (cloned when the paragraph is new, e.g. after a split) so the
 * new paragraph keeps its indent, bullet and alignment.
 */
function buildParaNode(pe: ParaEdit, lookup: SourceLookup, prefix: string): XmlNode {
  const srcNode = pe.src ? lookup(pe.src)?.node : undefined;
  const pNode = createElement(prefix ? `${prefix}:p` : 'p');
  if (srcNode) pNode.attrs = { ...srcNode.attrs };

  const pPr = srcNode ? child(srcNode, 'pPr') : undefined;
  if (pPr) pNode.children.push(cloneNode(pPr));

  // Paragraph formatting is applied to the *clone*, so the source tree is never
  // touched, and the element is created when the paragraph stated no properties
  // of its own — which is the common case.
  if (pe.format && !isEmptyFormat(pe.format)) {
    applyParaFormat(
      ensureParaProps(pNode, prefix),
      pe.format,
      prefix,
      pe.src ? resolvedOf(pe.src) : undefined,
    );
  }

  for (const seg of pe.segments) {
    if (!seg.isBreak && seg.text.length === 0) continue;
    pNode.children.push(buildRunNode(seg, lookup, prefix));
  }

  // endParaRPr gives an empty paragraph its height, so it must survive.
  const endPr = srcNode ? child(srcNode, 'endParaRPr') : undefined;
  if (endPr) pNode.children.push(cloneNode(endPr));

  return pNode;
}

/**
 * Rewrite a text body's paragraphs in place. Non-paragraph children
 * (`<a:bodyPr>`, `<a:lstStyle>`) keep their identity and leading position.
 */
export function writeTextBody(txBody: XmlNode, paras: ParaEdit[], lookup: SourceLookup): void {
  const prefix = drawingPrefix(txBody);
  const preamble = txBody.children.filter((c) => localName(c.name) !== 'p');
  const built = paras.map((pe) => buildParaNode(pe, lookup, prefix));

  // A text body must contain at least one paragraph.
  if (built.length === 0) built.push(createElement(prefix ? `${prefix}:p` : 'p'));

  txBody.children = [...preamble, ...built];
}
